#! /usr/bin/env sh

##Aliases
alias c='clear;'\
	n='nnn -e'\
	g='git'\
	vi='command vim'\
	xx='chmod +x'\
	ww="wget"\
	lz='lazygit'\
	nf='neofetch'\
	se='sudoedit'\
	nw='newsboat'\
	nf='neofetch'\
	cp='rsync'\
	uf='ufetch'\
	ls='exa -s type --git --icons'\
	ll='exa -s type -l --git --icons'\
	la='exa -s type -la --git --icons'\
	lla='exa -s type -la --git --icons'\
	lsa="exa -s type -a --git --icons"\
	vim='nvim'\
	cmd='command'\
	doo='doas'\
	del='doas rm -rf'\
	zzz='systemctl suspend'\
	bat='bat --style plain -P'\
	use='xrdb merge'\
	load='kill -USR1 $(pidof st)'\
	tree='exa --icons -s type -T --git'\
	mutt='neomutt'\
	magit='emacsclient -nc -e "(magit-status)"'\
	mkdir='mkdir -p'\
	server='python -m http.server'\
	\
	bspwm='startx ~/.config/X11/bspwm'\
	awesomewm='startx ~/.config/X11/awesome'\
	\
	pcomp='nvim +PackerCompile'\
	psync='nvim +PackerSync'
