alias n='nnn -e'
alias xx='chmod +x'
alias ww="wget"
alias lz='lazygit'
alias nf='neofetch'
alias se='sudoedit'
alias nw='newsboat'
alias nf='neofetch'
alias cp='rsync'
alias uf='ufetch'
alias ls='exa -s type --git --icons'
alias ll='exa -s type -l --git --icons'
alias la='exa -s type -la --git --icons'
alias lla='exa -s type -la --git --icons'
alias lsa="exa -s type -a --git --icons"
alias doo='doas'
alias del='doas rm -rf'
alias zzz='systemctl suspend'
alias bat='bat --style plain -P'
alias use='xrdb merge'
alias load='kill -USR1 (pidof st)'
alias tree='exa --icons -s type -T --git'
alias mutt='neomutt'
alias magit='emacsclient -nc -e "(magit-status)"'
alias mkdir='mkdir -p'
alias server='python -m http.server'

alias bspwm='startx ~/.config/X11/bspwm'
alias awesomewm='startx ~/.config/X11/awesome'
alias ddwm='startx ~/.config/X11/dwm'
alias qtil='startx ~/.config/X11/qtile'

alias pcomp='nvim +PackerCompile'
alias psync='nvim +PackerSync'

abbr c 'clear;'
