add_newline = false
format = """$character$all"""


[character]
#success_symbol = "[λ](green)"
#error_symbol = "[λ](red)"
#vicmd_symbol = "[ﬦ](blue)"
success_symbol = "[ ](green)"
error_symbol = "[ ](red)"
vicmd_symbol = "[ ](blue)"
disabled = false

[hostname]
ssh_only = false
format =  "[$hostname](bold blue) "
trim_at = "archlinux.org"
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = true
show_always = true
 
[directory]
read_only = " "
#home_symbol = "-"
truncation_length = 2
truncation_symbol = "… /"

[line_break]
disabled = true

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

