#! /usr/bin/env sh

##Aliases
alias g='git'
alias v='nvim'
alias c='clear;'
alias n='nnn -e'
alias :q='exit'
alias :e='$EDITOR'
alias xx='chmod +x'
alias ww="wget"
alias lg='lazygit'
alias nf='neofetch'
alias se='sudoedit'
alias nw='newsboat'
alias nf='neofetch'
alias cp='rsync'
alias uf='ufetch'
alias ls='exa --icons -s type --git'
alias ll='exa --icons -s type -l --git'
alias la='exa --icons -s type -la --git'
alias lla='exa --icons -s type -la --git'
alias lsa="exa --icons -s type -a --git"
alias doo='doas'
alias del='doas rm -rf'
alias zzz='systemctl suspend'
alias cat='bat --style plain -P'
alias vim='nvim'
alias use='xrdb merge'
alias load='kill -USR1 $(pidof st)'
alias tree='exa --icons -s type -T --git'
alias mutt='neomutt'
alias magit='emacsclient -nc -e "(magit-status)"'
alias mkdir='mkdir -p'
alias server='python -m http.server'

alias bspwm='startx ~/.config/X11/bspwm'
alias ddwm='startx ~/.config/X11/dwm'

