#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh 
bspc monitor -d I II III IV V 

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.00
bspc config borderless_monocle   true
bspc config gapless_monocle     false
bspc config focus_follows_pointer         true
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#4c566a"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a GNvim state=tiled

setxkbmap -model abnt2 -layout br -option ctrl:swapcaps &
xinput --set-prop "SIGMACHIP Usb Mouse" "Coordinate Transformation Matrix" 0.2 0 0 0 0.2 0 0 0 1 &
xsetroot -cursor_name left_ptr &
picom -f &
feh --bg-scale ~/Imgs/Void.jpg &
xrdb ~/.config/Xresources/OneDarkDarker &
