#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V 

bspc config border_width         1
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle     false
bspc config focus_follows_pointer         true
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#4c566a"

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

setxkbmap -model abnt2 -layout br -option caps:swapescape &
xinput --set-prop "SIGMACHIP Usb Mouse" "Coordinate Transformation Matrix" 0.2 0 0 0 0.2 0 0 0 1 &
xsetroot -cursor_name left_ptr &
picom &
feh --bg-scale ~/Imgs/wall/kurtco.jpg --no-fehbg &
xrdb ~/.config/Xresources/Nord &
sleep 10 &
$HOME/.config/polybar/launch.sh &
