
##Aliases
alias g 'git'
alias v 'nvim'
alias c 'clear;'
alias N 'nnn -e'
alias ww 'wget'
alias lg 'lazygit'
alias nf 'neofetch'
alias se 'sudoedit'
alias nw 'newsboat'
alias nf 'neofetch'
alias cp 'rsync'
alias uf 'ufetch'
alias ls 'exa --icons -s type --git'
alias ll 'exa --icons -s type -l --git'
alias la 'exa --icons -s type -la --git'
alias lla 'exa --icons -s type -la --git'
alias lsa 'exa --icons -s type -a --git'
alias doo 'doas'
alias del 'doas rm -rf'
alias zzz 'systemctl suspend'
alias cat 'bat --style plain -P'
alias vim 'nvim'
alias tree 'exa --icons -s type -T --git'
alias magit 'emacsclient -nc -e "(magit-status)"'
alias server 'python -m http.server'
alias startx 'startx ~/.config/X11/xinitrc'

